# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

oa.yctu.edu.cn	FALSE	/	FALSE	0	DomAuthSessId	E44C53850FEBA546AF02FD32FCAD5219
