# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_js.cltt.org	FALSE	/	FALSE	0	ASP.NET_SessionId	p30gyogkdkc02kqveo3scw1x
