# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_210.28.176.221	FALSE	/	FALSE	0	ASP.NET_SessionId	kqw1zb0ekf3l4jwey1vuskoc
