# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_211.65.1.251	FALSE	/	FALSE	0	ASP.NET_SessionId	tvf0sy4mb5yerfss1bmx4b41
