# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_211.65.1.251	FALSE	/	FALSE	0	ASP.NET_SessionId	a4tpaacd1z0fcnx1nahi3t0c
